### ISSUE TITLE
http://localhost:18880/admin/login.html   Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by GeoMSK** [kasimoglou/netsim#54]
When opening "http://localhost:18880/admin/login.html" I get an Internal Server Error.

```
Traceback (most recent call last):
  File "/home/george/netsim/netsim_py/src/bottle.py", line 942, in wsgi
    out = self._cast(self._handle(environ))
  File "/home/george/netsim/netsim_py/src/bottle.py", line 895, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3455, in wrapper
    return template(tpl_name, **tplvars)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3431, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3262, in render
    self.execute(stdout, env)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3254, in execute
    return self._include(env, subtpl, **rargs)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3239, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3249, in execute
    eval(self.co, env)
  File "/home/george/netsim/netsim_py/src/runner/web/mainpage.html", line 28, in <module>
    % if AAA.current_user_is_admin():
  File "/home/george/netsim/netsim_py/src/runner/AAA.py", line 52, in current_user_is_admin
    assert isinstance(user, User)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/netsim/netsim_py/src/bottle.py", line 850, in _handle
    return route.call(**args)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 670, in mountpoint_wrapper
    body = app(request.environ, start_response)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 967, in __call__
    return self.wsgi(environ, start_response)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 962, in wsgi
    start_response('500 INTERNAL SERVER ERROR', headers, sys.exc_info())
  File "/home/george/netsim/netsim_py/src/bottle.py", line 664, in start_response
    _raise(*exc_info)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 96, in _raise
    def _raise(*a): raise a[0](a[1]).with_traceback(a[2])
  File "/home/george/netsim/netsim_py/src/bottle.py", line 942, in wsgi
    out = self._cast(self._handle(environ))
  File "/home/george/netsim/netsim_py/src/bottle.py", line 895, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3455, in wrapper
    return template(tpl_name, **tplvars)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3431, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3262, in render
    self.execute(stdout, env)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3254, in execute
    return self._include(env, subtpl, **rargs)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3239, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3249, in execute
    eval(self.co, env)
  File "/home/george/netsim/netsim_py/src/runner/web/mainpage.html", line 28, in <module>
    % if AAA.current_user_is_admin():
  File "/home/george/netsim/netsim_py/src/runner/AAA.py", line 52, in current_user_is_admin
    assert isinstance(user, User)
AssertionError
```

**Comment by GeoMSK** [comment]
Error changed, happens when entering a username and password in http://localhost:18880/admin/login.html
probably beacause the user entered does not exist
Error: 500 Internal Server Error
Details:

The requested URL 'http://localhost:18880/admin/login.html' caused an error:

Internal Server Error
Exception:

BadRequest((BadRequest((...) , {'details': 'An unexpected error in the server has occurred'}), ()) , {'details': 'An unexpected error in the server has occurred'})

Traceback:

Traceback (most recent call last):
  File "/home/george/netsim/netsim_py/src/runner/api.py", line 40, in wrapper
    return func(_args, *_kwargs)
  File "/home/george/netsim/netsim_py/src/runner/api.py", line 255, in verify_password
    return Manager.get_user(username).password==password
AttributeError: 'NoneType' object has no attribute 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/netsim/netsim_py/src/bottle.py", line 850, in _handle
    return route.call(*_args)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 1721, in wrapper
    rv = callback(_a, *_ka)
  File "/home/george/netsim/netsim_py/src/bottle.py", line 3451, in wrapper
    result = func(_args, *_kwargs)
  File "/home/george/netsim/netsim_py/src/runner/admingui.py", line 76, in do_login
    if api.login(user, password):
  File "/home/george/netsim/netsim_py/src/runner/api.py", line 40, in wrapper
    return func(_args, **kwargs)
  File "/home/george/netsim/netsim_py/src/runner/api.py", line 260, in login
    success = username and verify_password(username, password)
  File "/home/george/netsim/netsim_py/src/runner/api.py", line 57, in wrapper
    raise BadRequest(details="An unexpected error in the server has occurred")
runner.apierrors.BadRequest: (BadRequest((...) , {'details': 'An unexpected error in the server has occurred'}), ())

**Comment by vsamtuc** [comment]
You need to recreate the database with the latest script.
It will create a user 'admin' with password 'admin'
You can then edit users via the admin gui.
